# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Travis Norton
tagline:             ''
description:         'Urban planning, transport geography, and GIS'
url:                 http://jtravisnorton.com
baseurl:             /about
paginate:            5

# About/contact
author:
  name:              Travis Norton
  url:               https://twitter.com/jtravisnorton
  email:             jtravisnorton@gmail.com

# Custom vars
version:             1.0.0
