# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Travis Norton
tagline:             ''
description:         'Urban planning, transport geography, and GIS.<br><a href="https://drive.google.com/file/d/0BxfBZhOp_a_AMHJIWFQ2R1d0U2s/view?usp=sharing" target="_blank">CV</a>/<a href="https://drive.google.com/file/d/0BxfBZhOp_a_ASEpXUjdxQzhnUlE/view?usp=sharing" target="_blank">Resume</a>'
url:                 http://jtravisnorton.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Travis Norton
  url:               https://twitter.com/jtravisnorton
  email:             jtravisnorton@gmail.com

# Custom vars
version:             1.0.0
